---
- name: Setup system groups
  become: yes
  with_items: '{{ system.users_and_groups }}'
  group:
    state: present
    name: '{{ item.name }}'
    gid: '{{ item.gid }}'
    system: '{{ item.system }}'

- name: Setup system users
  become: yes
  with_items: '{{ system.users_and_groups }}'
  user:
    state: present
    name: '{{ item.name }}'
    uid: '{{ item.uid }}'
    system: '{{ item.system }}'
    create_home: '{{ item.create_home }}'
    group: '{{ item.name }}'
    shell: '{{ item.shell }}'

- name: Add ansible user to groups
  become: yes
  with_items: '{{ system.user_groups }}'
  user:
    state: present
    name: '{{ ansible_user_id }}'
    append: yes
    groups: '{{ item }}'
