---
- hosts: localhost
  connection: local

  vars_files:
  - vars/main.yml

  roles:
  - firewall
  - autotime
  - role: hostname
    vars:
      hostname: '{{ system.hostname }}'
  - role: packages_official
    vars:
      official_packages: '{{ packages.main }}'
  - role: packages_aur
    vars:
      aur_packages: '{{ packages.aur }}'
  - role: packages_snap
    vars:
      snap_packages: '{{ packages.snap }}'
  - role: users
    vars:
      users: '{{ system.users }}'
  - role: user_groups
    vars:
      username: '{{ ansible_user_id }}'
      user_groups: '{{ system.user_groups }}'
  - ssh
  - shell
  - docker
