---
- hosts: localhost
  connection: local

  vars_files:
  - vars/main.yml

  roles:
  - firewall
  - autotime
  - hostname
  - role: packages_official
    vars:
      official_packages: "{{ packages.main }}"
  - role: packages_aur
    vars:
      aur_packages: "{{ packages.aur }}"
  - snap
  - users_and_roles
  - ssh
  - shell
  - docker
