---
- hosts: localhost
  connection: local

  vars_files:
  - vars/main.yml

  roles:
  - role: packages_official
    vars:
      jml_packages: "{{ packages.main }}"
  - role: packages_aur
    vars:
      jml_type: aur
      jml_packages: "{{ packages.aur }}"
  # - firewall
  # - autotime
  # - hostname
  # - packages
  # - snap
  # - users_and_roles
  # - ssh
  # - shell
  # - docker
