---
- hosts: localhost
  connection: local

  vars_files:
  - vars/main.yml

  roles:
  - role: packages2
    vars:
      type: pacman_main
      packages: "{{ packages.main }}"
  # - firewall
  # - autotime
  # - hostname
  # - packages
  # - snap
  # - users_and_roles
  # - ssh
  # - shell
  # - docker
