---
- name: Install pacman main packages
  become: yes
  when: jml_type == "pacman_main"
  with_items: "{{ jml_packages }}"
  community.general.pacman:
    executable: pacman
    state: present
    name: "{{ item }}"

- name: Install pacman dependent packages
  become: yes
  when: jml_type == "pacman_deps"
  with_items: "{{ jml_packages }}"
  community.general.pacman:
    executable: pacman
    state: present
    name: "{{ item }}"
    extra_args: "--asdeps"

- name: Install AUR packages
  when: jml_type == "aur"
  with_items: "{{ jml_packages }}"
  community.general.pacman:
    executable: yay
    state: present
    name: "{{ item.name }}"
    extra_args: {{ "--removemake" if item.remove_make }}
