---
-   name: Gather Facts (1)
    ansible.builtin.shell: 'which zsh'
    register: which_zsh
-   name: Gather Facts (2)
    ansible.builtin.set_fact:
        omz_zsh_path: "{{ which_zsh.stdout_lines[0] }}"
        omz_default_shell: "{{ lookup('ansible.builtin.env', 'SHELL') }}"
        omz_custom_path: "{{ ansible_env.HOME }}/.oh-my-zsh"
-   name: Check for oh-my-zsh
    stat:
        path: "{{ omz_custom_path }}"
    register: omz
-   name: Install oh-my-zsh
    ansible.builtin.shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended'
    when: not omz.stat.exists
-   name: Ensure ZSH_CUSTOM Directories Exist
    file:
        state: directory
        path: "{{ loop_var_custom_path }}"
        owner: "{{ ansible_user }}"
        mode: 0755
    with_items:
        - "{{ omz_custom_path }}/plugins"
        - "{{ omz_custom_path }}/themes"
    loop_control:
        loop_var: "loop_var_custom_path"
-   name: Get Custom Plugins
    git:
        repo: "{{ loop_var_custom_plugin.repo }}"
        dest: "{{ omz_custom_path }}/plugins/{{ loop_var_custom_plugin.dest }}"
        update: yes
    with_items: "{{ omz_custom_plugins }}"
    loop_control:
        loop_var: "loop_var_custom_plugin"
-   name: Disable Current Plugins
    ansible.builtin.shell:
        cmd: >-
            zsh -c 'source "{{ ansible_env.HOME }}/.zshrc"; if [[ -n "${plugins[*]}" ]]; then omz plugin disable "${plugins[@]}"; fi'
-   name: Fix plugins variable definition
    ansible.builtin.shell:
        cmd: sed -i 's|^plugins=$|plugins=()|' "{{ ansible_env.HOME }}/.zshrc"
-   name: Enable Plugins
    ansible.builtin.shell:
        cmd: >-
            zsh -c 'source "{{ ansible_env.HOME }}/.zshrc"; omz plugin enable "{{ loop_var_plugin_enable }}"'
    with_items: "{{ omz_enabled_plugins }}"
    loop_control:
        loop_var: "loop_var_plugin_enable"
# -   name: Change Default Shell
#     ansible.builtin.shell: chsh -s "{{ omz_zsh_path }}"
#     # when: omz_default_shell is match("{{ omz_zsh_path }}")1p
#     when: omz_default_shell == omz_zsh_path
