---
- name: Install and configure Oh-My-Zsh
  # ansible.builtin.include_role:
  #   name: coreyramirezgomez.ohmyzsh
  # vars:
  #   ohmyzsh_plugins: '{{ oh-my-zsh-config.builtin-plugins }}'
  #   ohmyzsh_custom_plugins: '{{ oh-my-zsh-config.custom-plugins }}'
  coreyramirezgomez.ohmyzsh:
    ohmyzsh_plugins: '{{ oh-my-zsh-config.builtin-plugins }}'
    ohmyzsh_custom_plugins: '{{ oh-my-zsh-config.custom-plugins }}'


- name: Install and configure PowerLevel10k theme for Oh-My-Zsh
  ansible.builtin.include_role:
    name: diodonfrost.p10k
  vars:
    zsh_plugin: ohmyzsh
    p10k_prompt_style: rainbow
    p10k_prompt_time: 12-hour
    p10k_prompt_separator: angled
    p10k_prompt_head: sharp
    p10k_prompt_tails: flat
    p10k_prompt_height: two-lines
    p10k_prompt_connection: solid
    p10k_prompt_connection_color: lightest
    p10k_prompt_frame: no
    p10k_prompt_spacing: compact
    p10k_prompt_flow: concise
    p10k_transient_prompt: no
# - role: coreyramirezgomez.ohmyzsh
  #   ohmyzsh_plugins: '{{ oh-my-zsh-config.builtin-plugins }}'
  #   ohmyzsh_custom_plugins: '{{ oh-my-zsh-config.custom-plugins }}'
  # - role: diodonfrost.p10k
  #   zsh_plugin: ohmyzsh
  #   p10k_prompt_style: rainbow
  #   p10k_prompt_time: 12-hour
  #   p10k_prompt_separator: angled
  #   p10k_prompt_head: sharp
  #   p10k_prompt_tails: flat
  #   p10k_prompt_height: two-lines
  #   p10k_prompt_connection: solid
  #   p10k_prompt_connection_color: lightest
  #   p10k_prompt_frame: no
  #   p10k_prompt_spacing: compact
  #   p10k_prompt_flow: concise
  #   p10k_transient_prompt: no