---
- name: Setup system groups
  become: yes
  with_items: '{{ users }}'
  group:
    state: present
    name: '{{ item.name }}'
    gid: '{{ item.gid }}'
    system: '{{ item.system }}'

- name: Setup system users
  become: yes
  with_items: '{{ users }}'
  user:
    state: present
    name: '{{ item.name }}'
    uid: '{{ item.uid }}'
    system: '{{ item.system }}'
    create_home: '{{ item.create_home }}'
    group: '{{ item.name }}'
    shell: '{{ item.shell }}'
