- name: Install Docker
  become: true
  pacman:
    name: docker
    state: present
  tags:
    - docker

- name: Enable Docker service
  become: true
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  become: true
  with_items: '{{ docker_users }}'
  user:
    name: '{{ item }}'
    groups: 'docker'
    append: 'yes'
