---
- name: Install AUR packages
  with_items: "{{ aur_packages }}"
  kewlfft.aur.aur:
    use: yay
    name: "{{ item.name }}"
    state: present
    extra_args: "{{ '--removemake' if item.remove_make }}"
    aur_only: yes
