---
- name: Install pacman main packages
  become: yes
  when: type == "pacman_main"
  with_items: "{{ packages }}"
  community.general.pacman:
    state: latest
    name: "{{ item }}"

# - name: Install dependent packages
#   become: yes
#   with_items: "{{ packages.addon }}"
#   community.general.pacman:
#     extra_args: "--asdeps"
#     state: present
#     name: "{{ item }}"

# - name: Install AUR packages
#   with_items: "{{ packages.aur }}"
#   community.general.pacman:
#     executable: yay
#     state: present
#     name: "{{ item }}"

# - name: Install AUR packages and remove make packages
#   with_items: "{{ packages.aur_remove_make }}"
#   community.general.pacman:
#     executable: yay
#     extra_args: "--removemake"
#     state: present
#     name: "{{ item }}"
